---
# tasks file for ansible-role-zerotier

- block:
    - import_tasks: leave_network.yml
      when:
        - zerotier_network_id is defined
        - ansible_local['zerotier']['networks'][zerotier_network_id] is defined
        - ansible_local['zerotier']['networks'][zerotier_network_id]['status'] == 'OK'

    - import_tasks: deauthorize_node.yml
      when:
        - zerotier_api_accesstoken | length > 0
        - ansible_local['zerotier']['node_id'] is defined

    - import_tasks: uninstall.yml

  when:
    - state | default('present') == 'absent'

- block:
    - import_tasks: install.yml
      when:
        - not skip_install | default(false) | bool

    - name: Update ansible_local facts
      script: set_facts.sh

    - name: Re-gather ansible_local facts
      setup: filter=ansible_local

    - import_tasks: authorize_node.yml
      when:
        - zerotier_api_accesstoken | length > 0
        - ansible_local['zerotier']['node_id'] is defined

    - import_tasks: join_network.yml
      when:
        - zerotier_network_id is defined

  when:
    - state | default('present') != 'absent'